### Sign Up
POST http://localhost:8080/users/signup
content-type: application/json

{
  "email": "ivan@bbcag.ch",
  "password": "12345678",
  "username": "Ivan"
}

### Sign In
POST http://localhost:8080/users/signin
content-type: application/json

{
  "email": "admin@bbcag.com",
  "password": "admin1234"
}

> {%
    client.global.set("auth_token", response.body.token);
%}
